services:
  # The Database container
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: horkovcode
      POSTGRES_PASSWORD: 'password'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  # graphical UI client for Postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  # Owner Service
  owner:
    container_name: owner
    image: nickl0gist/owner:0.1
    ports:
      - "8077:8077"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
    depends_on:
      - postgres
  # Client Service
  client:
    container_name: client
    image: nickl0gist/client:0.1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
    depends_on:
      - postgres
# network communication
networks:
  postgres:
    driver: bridge

# Volumes to store data
volumes:
  postgres:
  pgadmin: